encoder: vitb
min_depth: 0.000001
max_depth: 1.0
lr: 5e-6
use_huggingface: False
safetensor_path: /home/loick/DL-FOLDER/Depth-any-canopy/pretrained_model/depth-any-canopy-base.safetensors

freeze_parts:
  - pretrained