encoder: vits
min_depth: 0.000001
max_depth: 1.0
lr: 1e-4
use_huggingface: False
safetensor_path: /home/loick/DL-FOLDER/Depth-any-canopy/pretrained_model/depth-any-canopy-small.safetensors
#/home/loick/DL-FOLDER/train-FT-285E21_CHM_015-depth-any-canopy-small-2025-06-08 01:00:51/checkpoints/depth-any-canopy-epoch=24-val_loss=0.01.ckpt

freeze_parts:
  - pretrained
  # - depth_head.projects
  # - depth_head.resize_layers
  # - depth_head.scratch