is_inference_only: True
images_folder_path: /home/loick/DL-FOLDER/Depth-any-canopy/rgb_LIDAR/dataset/rbg_images
chm_folder_path: /home/loick/DL-FOLDER/Depth-any-canopy/rgb_LIDAR/dataset/targets
split_ratio: 0.2
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
batch_size: 32
num_workers: 5
patch_size: 518
overlap_ratio: 0.15
ndvi_threshold: 0.1
split_type: horizontal
top_side_as_train: False
visualize_patches: True

isolate_test_source_tiff_path: /home/loick/DL-FOLDER/Depth-any-canopy/rgb_LIDAR/dataset/images/285E26_GeoTiff_cut.tif
isolate_test_reference_tiff_path: /home/loick/DL-FOLDER/Depth-any-canopy/rgb_LIDAR/dataset/images/285E26_CHM_015.tif